// Generated by ESG at 2021-10-19 20:12:56. github.com/simplefelix/esg

package test

import "fmt"

type TestErr struct {
	_extra_ interface{}
	msg interface{}
}

// ErrorCode change it as you prefer.
func (e TestErr) ErrorCode() interface{} {
	return "TestErr"
}

// StatusCode refers to http response status code.
// Developer may want to set response status code based on error.
// For example, if the error is caused by bad request, then change the return value to 400.
// Ignore this function if no need for your project.
func (e TestErr) StatusCode() int {
	return 500
}

// Extra returns _extra_ which can be set by user. Usage of _extra_ is determined by user.
func (e TestErr) Extra() interface{} {
	return e._extra_
}

// SetExtra sets _extra_ with a value by user. Usage of _extra_ is determined by user.
func (e *TestErr) SetExtra(extra interface{}) {
	e._extra_ = extra
}

// Error implementation to error interface.
func (e TestErr) Error() string {
	return fmt.Sprintf(`%v`, e.msg)
}

// ErrTestErr is convenient constructor.
func ErrTestErr(msg interface{}) TestErr {
	return TestErr{
		msg: msg,
	}
}
